let productItemsData = [
    {
      id: "jfhgbvnscs",
      name: "Vintage Shirt",
      price: 405,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae, illum.",
      img: "images/f1.jpg",
    },
    {
      id: "ioytrhndcv",
      name: "Earpod",
      price: 100,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      img: "images/product2.jpg",
    },
    {
      id: "wuefbncxbsn",
      name: "Orange sneakers",
      price: 250,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Recusandae, illum.",
      img: "images/shoe3.png",
    },
    {
      id: "thyfbcv",
      name: "Kaki shirt",
      price: 400,
      desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
      img: "images/n7.jpg",
    },
    {
        id: "thfgghcbcv",
        name: "Denim shirt",
        price: 50,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "images/f6.jpg",
    },
    {
        id: "ggrhfhcbcv",
        name: "Nike Air MAX",
        price: 240,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "images/shoe3a.png",
    },
    {
        id: "aaaehcbcv",
        name: "Sunglasses",
        price: 120,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "images/product5.jpg",
    },
    {
        id: "rrgdfhcbcv",
        name: "Adidas Baseball Cap",
        price: 300,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit.",
        img: "images/product6.jpg",
      },
  ];